crud/crud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('olx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)















# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',include('shop.urls')),
#     path('search/',include('search.urls')),
#     path('cart/',include('cart.urls')),

crud/olx/urls.py
from django.contrib import admin
from django.urls import path,include
from olx import views
app_name="olx"

urlpatterns = [
    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    path('add/',views.add,name='add'),
    path('view/',views.view,name='view'),
    path('detail/<int:pk>/',views.detail.as_view(),name='detail'),
    path('update/<int:pk>/', views.update.as_view(), name='update'),
    path('delete/<int:n>/', views.delete, name="delete"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

]

crud/olx/models.py
from django.db import models


# Create your models here.

class product(models.Model):
    product_name=models.CharField(max_length=50)
    product_price=models.IntegerField()
    year_reg=models.CharField(max_length=50)
    product_image=models.ImageField(upload_to="olx/media",null=True,blank=True)
    product_desc=models.CharField(max_length=50)

    def __str__(self):
        return self.product_name

crud/olx/views.py
from django.shortcuts import render,redirect
from .models import product
from django.views.generic import DetailView,DeleteView,UpdateView
from django.urls import  reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def base(request):
    return render(request,'base.html')

def home(request):
     return render(request,'home.html')

# def register(request):
#     return render(request,'register.html')


def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        e = request.POST['e']
        f = request.POST['f']
        l = request.POST['l']
        if(cp==p):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
            return  redirect('olx:home')
        else:
            return HttpResponse("passwords are not same")
    return render(request,'register.html')
@login_required
def add(request):
    if(request.method=="POST"):
        n=request.POST['n']
        p=request.POST['p']
        y=request.POST['y']
        d=request.POST['d']
        i=request.FILES['i']
        m=product.objects.create(product_name=n,product_price=p,year_reg=y,product_desc=d,product_image=i)
        m.save()
        return home(request)
    return render(request,'add.html')
@login_required
def view(request):
    a=product.objects.all()
    return render(request,'view.html',{'a':a})

# def update(request):
#     return render(request,'update.html')

class update(UpdateView):
    model=product
    template_name='update.html'
    fields=['product_name','product_price','product_desc','year_reg','product_image',]
    success_url=reverse_lazy('olx:view')

class detail(DetailView):
    model=product
    template_name = "detail.html"
    context_object_name ="a"


def delete(request,n):
    m=product.objects.get(id=n)
    m.delete()
    return home(request)
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('olx:home')
        else:
            return HttpResponse("invalid Credentials")
    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

crud/olx/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add Product
{% endblock %}
{% block content %}
<h1>Add Product</h1>
<h4> This page is used to add Product </h4>
<form method="POST" enctype="multipart/form-data" >
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Product_name</label>
    <input type="text" class="form-control"  name="n" placeholder="Enter Product Name">
  </div>

    <div class="mb-3">
    <label class="form-label">Product_price</label>
    <input type="number" class="form-control"  name="p" placeholder="Enter Product price">
  </div>

      <div class="mb-3">
    <label class="form-label">Product_year</label>
    <input type="number" class="form-control"  name="y" placeholder="Enter Product Year">
  </div>
      <div class="mb-3">
    <label class="form-label">Product_desc</label>
    <input type="text" class="form-control"  name="d" placeholder="Enter Product Description">
  </div>
      <div class="mb-3">
    <label class="form-label">Product_Image</label>
    <input type="file" class="form-control"  name="i" placeholder="Add Product Image">
  </div>
      <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

crud/olx/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'olx:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'olx:add' %}">Add</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'olx:view' %}">View</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'olx:logout' %}">Logout</a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'olx:login' %}">login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olx:register' %}">Register</a>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

crud/olx/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-4 ms-4">

        <div class="col-md-6">
            <img src="{{a.product_image.url}}" height="400px" width="90%" style="border-radius:10px;">
        </div>
        <div class="col-md-6">
            <h3 class="fw-bold">{{a.product_name}}</h3>
            <p><i>{{a.product_price}}</i></p>
            <p><i>{{a.year_reg}}</i></p>
            <p>{{a.product_desc}}</p>
            <a href="{% url 'olx:update' a.id %}" class="btn btn-success">UPDATE</a>
            <a href="{% url 'olx:delete' a.id %}" class="btn btn-danger">DELETE</a>
        </div>
        </div>
</div>
{% endblock %}

crud/olx/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
<h1>Welcome to home page</h1>
{% endblock %}

crud/olx/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
login
{% endblock %}

{% block content %}
<h1>Login</h1>
<h4>This is login page </h4>
<form method="POST">
  {% csrf_token %}
<form>
  <div class="mb-3">
    <label class="form-label">User name</label>
    <input type="text" class="form-control" name="u" placeholder=" Enter User name">
  </div>
       <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder=" Enter password">
  </div><br>
     <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form>
{% endblock %}

crud/olx/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
register
{% endblock %}
{% block content %}
<h1>Register</h1>
<form method="POST">
  {% csrf_token %}
<form>
  <div class="mb-3">
    <label class="form-label">User name</label>
    <input type="text" class="form-control" name="u" placeholder=" Enter User name">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder=" Enter Password">
  </div>
    <div class="mb-3">
    <label class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" placeholder=" Enter Confirm Password">
  </div>
     <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter email">
          <div class="mb-3">
    <label class="form-label">First Name</label>
    <input type="text" class="form-control" name="f" placeholder=" Enter First Name">
  </div>
   <div class="mb-3">
    <label class="form-label">Last Name</label>
    <input type="text" class="form-control" name="l" placeholder=" Enter Last Name">
  </div>

  </div>


  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form><br><br>

{% endblock %}

crud/olx/templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
edit page
{% endblock %}
{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {%csrf_token%}

  {{form}}
    <input type="submit">
</form>
{% endblock %}

crud/olx/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%load static%}
{% block title%}
home page
{% endblock %}
{% block content %}
<section class="mt-2">
    <div class="container">
        <div class="row">
           {% for i in a %}
            <div class="col-md-3">
             <div class="card" style="width: 17rem;height:500px;border-radius:12px;">
  <img src="{{i.product_image.url}}" class="card-img-top" alt="..." style="height:350px;width:100%;border-radius:12px;">
  <div class="card-body">
    <h5 class="card-title">{{i.product_name}}</h5>
    <p class="card-text">{{i.product_desc}}</p>
      <a href="{% url 'olx:detail' i.id %}" class=" btn btn-secondary"> more details</a>
  </div>
</div>
 </div>

            {% endfor %}
        </div>
    </div>
</section>
{%endblock%}